### ISSUE TITLE
Inputting log-binomial model gives Error: No tidy method for objects of class qr

### ISSUE THREAD

**Issue by ashjudge** [josherrickson/howManyImputations#4] opened 2024-02-09 02:06 UTC
Hi Josh, thanks for developing this package. I used mice for multiple imputation to create my dataset "completed2" and am conducting log-binomial regression using categorical independent and dependent variables. Here's a simplified example of my code:

```
try <- with(completed2, glm(PTB2 ~ v1_depression_cat, family=binomial(link="log")))
how_many_imputations(try)
```

I'm getting the following error:

Error: No tidy method for objects of class qr
In addition: Warning messages:
1: In get.dfcom(object, dfcom) : Infinite sample size assumed.
2: 'tidy.numeric' is deprecated.
See help("Deprecated") 
3: 'tidy.numeric' is deprecated.
See help("Deprecated") 
4: 'tidy.numeric' is deprecated.
See help("Deprecated") 
5: 'tidy.numeric' is deprecated.
See help("Deprecated") 
6: 'tidy.numeric' is deprecated.
See help("Deprecated") 
7: 'tidy.numeric' is deprecated.
See help("Deprecated") 

I'm not sure if this is something about the program or if it's an error on my end. Thanks for any feedback you may have!

**Comment by josherrickson** [comment] 2024-02-09 14:01
Thanks for the report. Can you provide the output of a `traceback()` call? Are all your packages up-to-date? Are you able to share your data (privately) or a reproducible example?

**Comment by ashjudge** [comment] 2024-02-09 15:34
I think it's because tidyr isn't up to date. I'm having to reinstall software on my Mac. I'll update if it doesn't resolve, but I think it will.

**Comment by josherrickson** [comment] 2024-02-19 12:22
Going to close this, feel free to re-open if it turns out the update didn't resolve it.

**Closed as completed by josherrickson** 2024-02-19 12:22 UTC
